services:
  - type: web
    name: unveiling
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        sync: false
      - key: OPENAI_MODEL_NAME
        sync: false
      - key: SERPER_API_KEY
        sync: false
